### ISSUE TITLE
WSL/Linux Fix for those who can't connect to http://localhost:7860

### ISSUE THREAD

**Issue by PeterTucker** [JarodMica/ai-voice-cloning#106]
A few others have found this solution, but I thought I'd clearly post a fix:

1. change this line (34, I believe) in src/main.py:
```
webui.launch(share=args.share, prevent_thread_lock=True, show_error=True, server_name=listen_host, server_port=args.li>
```
to...
```
webui.launch(share=args.share, prevent_thread_lock=True, show_error=True, server_name="0.0.0.0", server_port=args.li>
```

2. Remove the ai-voice-cloning image if you already built it: ```docker image rm ai-voice-cloning```
3. Build the image again: ```./setup-docker.sh```
4. Start the container again: ```./start-docker.sh```
5. In your browser: ```http://localhost:7860```

**Comment by kimabjorkede** [comment]
I had to change it to:

```
webui.launch(share=args.share, prevent_thread_lock=True, show_error=True, server_name="0.0.0.0", server_port=args.listen_port)
```

**Comment by PeterTucker** [comment]
@kimabjorkede Not sure why markdown cut off my answer, but yeah that's correct.

**Comment by mekler22** [comment]
> I had to change it to:
> 
> ```
> webui.launch(share=args.share, prevent_thread_lock=True, show_error=True, server_name="0.0.0.0", server_port=args.listen_port)
> ```

I've tried that, it say that its sharing on http://0.0.0.0:7860 but I cannot access that address. tried both with the server name and the server IP. any ideas?
