### ISSUE TITLE
Unknown method

### ISSUE THREAD

**Issue by HarryBols** [JarodMica/ai-voice-cloning#11]
Whenever i unzip I get these errors
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\distlib\t64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\distlib\w64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\installer\_scripts\t64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\installer\_scripts\w64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\setuptools\cli-arm64.exe
ai-voice-cloning.7z: Unknown method in ai-voice-cloning\runtime\Lib\site-packages\setuptools\gui-arm64.exe

**Comment by JarodMica** [comment]
This may happen if you 7zip is out of date or you used a different extractor, check to see that it's updated.

**Comment by Vektor369** [comment]
Downloaded the latest 7zip. Still doesn't work.
