### ISSUE TITLE
Please provide LINUX comaptible version for fairseq, deepspeed and pyfastmp3decoder 

### ISSUE THREAD

**Issue by sanihaq** [JarodMica/ai-voice-cloning#131]
I understand you are focused on windows specific features and compatability. but please provide linux support or at least provide instruction on how to build on linux. Also update readme with updated information, it will help a lot of people i think, Thank you.

**Comment by traderpedroso** [comment]
> I understand you are focused on windows specific features and compatability. but please provide linux support or at least provide instruction on how to build on linux. Also update readme with updated information, it will help a lot of people i think, Thank you.

have you checked notebook_colab or paperspace

**Comment by testujemai** [comment]
+1 That would really help more of us
