### ISSUE TITLE
Include pyfastmp3decoder in the site-packages

### ISSUE THREAD

**Issue by IDerr** [JarodMica/ai-voice-cloning#15]
Hello,

would be great to add the pyfastmp3decoder used by the project to handle mp3 files natively !

Right now, it crashes when trained with mp3 files

thanks for your work,

**Comment by aWalker-0** [comment]
Were you ablet to do a work-around, or manually add pyfastmp3decorder to the package? I'm also running into the same problem.

**Comment by IDerr** [comment]
I converted all my mp3 to wav using ffmpeg, but should be doable to add the package

**Comment by aWalker-0** [comment]
Gotcha. I ended up just converting them as well.

**Comment by JarodMica** [comment]
> Hello,
> 
> would be great to add the pyfastmp3decoder used by the project to handle mp3 files natively !
> 
> Right now, it crashes when trained with mp3 files
> 
> thanks for your work,

It's in the code, though, I'll have to test to make sure it doesn't blow things up!
