### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:

### ISSUE THREAD

**Issue by UncleBob2** [JarodMica/ai-voice-cloning#19]
Checking CUDA availability and Torch installation...
CUDA available: True
Torch version: 2.1.2+cu118
Running main.py...
Whisper detected
Traceback (most recent call last):
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\src\utils.py", line 98, in <module>
    from vall_e.emb.qnt import encode as valle_quantize
ModuleNotFoundError: No module named 'vall_e'

Bark detected
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading TorToiSe... (AR: C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\models\tortoise\autoregressive.pth, diffusion: ./models/tortoise/diffusion_decoder.pth, vocoder: bigvgan_24khz_100band)
Hardware acceleration found: cuda
use_deepspeed api_debug False
Some weights of the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.encoder.pos_conv_embed.conv.weight_v', 'wav2vec2.encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at jbetker/wav2vec2-large-robust-ft-libritts-voxpopuli and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loading tokenizer JSON: ./modules/tortoise-tts/tortoise/data/tokenizer.json
Loaded tokenizer
Loading autoregressive model: C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\models\tortoise\autoregressive.pth
Traceback (most recent call last):
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\src\main.py", line 34, in <module>
    tts = load_tts()
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\src\utils.py", line 3692, in load_tts
    tts = TorToise_TTS(minor_optimizations=not args.low_vram,
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\src\tortoise\api.py", line 308, in __init__
    self.load_autoregressive_model(autoregressive_model_path)
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\src\tortoise\api.py", line 391, in load_autoregressive_model
    self.autoregressive.load_state_dict(torch.load(self.autoregressive_model_path))
  File "C:\Users\aiwinsor\Documents\dev\ai-voice-cloning\runtime\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnifiedVoice:
        Unexpected key(s) in state_dict: "gpt.h.0.attn.bias", "gpt.h.0.attn.masked_bias", "gpt.h.1.attn.bias", "gpt.h.1.attn.masked_bias", "gpt.h.2.attn.bias", "gpt.h.2.attn.masked_bias", "gpt.h.3.attn.bias", "gpt.h.3.attn.masked_bias", "gpt.h.4.attn.bias", "gpt.h.4.attn.masked_bias", "gpt.h.5.attn.bias", "gpt.h.5.attn.masked_bias", "gpt.h.6.attn.bias", "gpt.h.6.attn.masked_bias", "gpt.h.7.attn.bias", "gpt.h.7.attn.masked_bias", "gpt.h.8.attn.bias", "gpt.h.8.attn.masked_bias", "gpt.h.9.attn.bias", "gpt.h.9.attn.masked_bias", "gpt.h.10.attn.bias", "gpt.h.10.attn.masked_bias", "gpt.h.11.attn.bias", "gpt.h.11.attn.masked_bias", "gpt.h.12.attn.bias", "gpt.h.12.attn.masked_bias", "gpt.h.13.attn.bias", "gpt.h.13.attn.masked_bias", "gpt.h.14.attn.bias", "gpt.h.14.attn.masked_bias", "gpt.h.15.attn.bias", "gpt.h.15.attn.masked_bias", "gpt.h.16.attn.bias", "gpt.h.16.attn.masked_bias", "gpt.h.17.attn.bias", "gpt.h.17.attn.masked_bias", "gpt.h.18.attn.bias", "gpt.h.18.attn.masked_bias", "gpt.h.19.attn.bias", "gpt.h.19.attn.masked_bias", "gpt.h.20.attn.bias", "gpt.h.20.attn.masked_bias", "gpt.h.21.attn.bias", "gpt.h.21.attn.masked_bias", "gpt.h.22.attn.bias", "gpt.h.22.attn.masked_bias", "gpt.h.23.attn.bias", "gpt.h.23.attn.masked_bias", "gpt.h.24.attn.bias", "gpt.h.24.attn.masked_bias", "gpt.h.25.attn.bias", "gpt.h.25.attn.masked_bias", "gpt.h.26.attn.bias", "gpt.h.26.attn.masked_bias", "gpt.h.27.attn.bias", "gpt.h.27.attn.masked_bias", "gpt.h.28.attn.bias", "gpt.h.28.attn.masked_bias", "gpt.h.29.attn.bias", "gpt.h.29.attn.masked_bias".
Press any key to continue . . .

**Comment by JarodMica** [comment]
Did the package extract without any error?  It seems that possibly a file is missing or may be corrupt.

**Comment by UncleBob2** [comment]
thanks I will give it a try. Maybe we need to modify the requirements.txt .

**Comment by UncleBob2** [comment]
Go to \ ai-voice-cloning-v2_0\ai-voice-cloning\src\tortoise

open text editor to edit file "api.py"

line 341 is the beginning of the function     

def load_autoregressive_model(self, autoregressive_model_path, is_xtts=False):

To modify the load_autoregressive_model function to handle unexpected keys, you can follow these steps:

Load the state dictionary without strict mode (strict=False). This will ignore unexpected keys.

Get the unexpected keys from the state dictionary after loading.

Print the unexpected keys to the console for debugging purposes.

Remove the unexpected keys from the state dictionary.

Load the state dictionary into the model.

def load_autoregressive_model(self, autoregressive_model_path, is_xtts=False):
    if hasattr(self,"autoregressive_model_path") and os.path.samefile(self.autoregressive_model_path, autoregressive_model_path):
        return

    self.autoregressive_model_path = autoregressive_model_path if autoregressive_model_path and os.path.exists(autoregressive_model_path) else get_model_path('autoregressive.pth', self.models_dir)
    new_hash = hash_file(self.autoregressive_model_path)

    if hasattr(self,"autoregressive_model_hash") and self.autoregressive_model_hash == new_hash:
        return

    self.autoregressive_model_hash = new_hash

    self.loading = True
    print(f"Loading autoregressive model: {self.autoregressive_model_path}")

    if hasattr(self, 'autoregressive'):
        del self.autoregressive

    # XTTS requires a different "dimensionality" for its autoregressive model
    if new_hash == "e4ce21eae0043f7691d6a6c8540b74b8" or is_xtts:
        dimensionality = {
            "max_mel_tokens": 605,
            "max_text_tokens": 402,
            "max_prompt_tokens": 70,
            "max_conditioning_inputs": 1,
            "layers": 30,
            "model_dim": 1024,
            "heads": 16,
            "number_text_tokens": 5023, # -1
            "start_text_token": 261,
            "stop_text_token": 0,
            "number_mel_codes": 8194,
            "start_mel_token": 8192,
            "stop_mel_token": 8193,
        }
    else:
        dimensionality = {
            "max_mel_tokens": 604,
            "max_text_tokens": 402,
            "max_conditioning_inputs": 2,
            "layers": 30,
            "model_dim": 1024,
            "heads": 16,
            "number_text_tokens": 255,
            "start_text_token": 255,
            "checkpointing": False,
            "train_solo_embeddings": False
        }

    self.autoregressive = UnifiedVoice(**dimensionality).cpu().eval()
    
    # Load the state dictionary without strict mode
    state_dict = torch.load(self.autoregressive_model_path)
    unexpected_keys = state_dict.keys() - self.autoregressive.state_dict().keys()
    
    # Print the unexpected keys for debugging
    if unexpected_keys:
        print(f"Unexpected keys found in state_dict: {unexpected_keys}")
    
    # Remove unexpected keys from the state dictionary
    for key in unexpected_keys:
        state_dict.pop(key)
    
    # Load the state dictionary into the model
    self.autoregressive.load_state_dict(state_dict, strict=False)
    
    self.autoregressive.post_init_gpt2_config(use_deepspeed=self.use_deepspeed, kv_cache=self.use_kv_cache)
    if self.preloaded_tensors:
        self.autoregressive = migrate_to_device(self.autoregressive, self.device)

    self.loading = False
    print(f"Loaded autoregressive model")
