### ISSUE TITLE
Iteration/Sample setting does not affect output quality when Hifigan is ON

### ISSUE THREAD

**Issue by michelleeechan** [JarodMica/ai-voice-cloning#21]
It appears that when the Hifigan is turned ON, increasing the "diffusion iteration" and the "number of autoregressive samples" does not have any noticeable effect on the quality and generating time of the output.

I compared the output quality at different samples / iterations with the Hifigan both ON and OFF, using the same model and voice samples, 
(libraries are those preinstalled in the 7zip)

With Hifigan OFF:
**iteration=2 sample=2,** the output is garbled, cannot hear any clear words,  iteration time= 18 secs
**iteration= 512 sample= 512** the output has very good quality,  iteration time = very very long

With Hifigan ON:
**iteration=2 sample=2,** the output is acceptable, iteration time=2.96secs
**iteration=512 sample=512** , the output is acceptable without noticeable improvement,  iteration time is also unchanged =2.96secs

-

Besides, the output with HifiGan ON sounds choppy.
https://github.com/JarodMica/ai-voice-cloning/assets/51301116/ec3e4ca8-2359-4a9b-a5b3-1be1a05af10f

Below is the HifiGan OFF output.
https://github.com/JarodMica/ai-voice-cloning/assets/51301116/d08612e8-3291-4d26-bab6-d038bf11233b

-

may i know is this normal or just me? 

Thank you very much for your time.

**Comment by JarodMica** [comment]
> It appears that when the Hifigan is turned ON, increasing the "diffusion iteration" and the "number of autoregressive samples" does not have any noticeable effect on the quality and generating time of the output.
> 
> I compared the output quality at different samples / iterations with the Hifigan both ON and OFF, using the same model and voice samples, (libraries are those preinstalled in the 7zip)
> 
> With Hifigan OFF: **iteration=2 sample=2,** the output is garbled, cannot hear any clear words, iteration time= 18 secs **iteration= 512 sample= 512** the output has very good quality, iteration time = very very long
> 
> With Hifigan ON: **iteration=2 sample=2,** the output is acceptable, iteration time=2.96secs **iteration=512 sample=512** , the output is acceptable without noticeable improvement, iteration time is also unchanged =2.96secs
> 
> 
> Besides, the output with HifiGan ON sounds choppy. https://github.com/JarodMica/ai-voice-cloning/assets/51301116/ec3e4ca8-2359-4a9b-a5b3-1be1a05af10f
> 
> Below is the HifiGan OFF output. https://github.com/JarodMica/ai-voice-cloning/assets/51301116/d08612e8-3291-4d26-bab6-d038bf11233b
> 
> 
> may i know is this normal or just me?
> 
> Thank you very much for your time.

Hi Michell, 

Your observation is correct.  When you turn HifiGAN on, it replaces the diffusion component of the pipeline and since sample and iterations are specific to the diffusion component, it has no effect.

When you turn HifiGAN off, it loads the diffusion model and you can now play around with iteration and sample.  512 for sample is quite extreme and I'd never suggest going that high as the cost/performance isn't worth it.  My suggestion would be 32 at max for samples.

**Comment by michelleeechan** [comment]
> > It appears that when the Hifigan is turned ON, increasing the "diffusion iteration" and the "number of autoregressive samples" does not have any noticeable effect on the quality and generating time of the output.
> > I compared the output quality at different samples / iterations with the Hifigan both ON and OFF, using the same model and voice samples, (libraries are those preinstalled in the 7zip)
> > With Hifigan OFF: **iteration=2 sample=2,** the output is garbled, cannot hear any clear words, iteration time= 18 secs **iteration= 512 sample= 512** the output has very good quality, iteration time = very very long
> > With Hifigan ON: **iteration=2 sample=2,** the output is acceptable, iteration time=2.96secs **iteration=512 sample=512** , the output is acceptable without noticeable improvement, iteration time is also unchanged =2.96secs
> > Besides, the output with HifiGan ON sounds choppy. https://github.com/JarodMica/ai-voice-cloning/assets/51301116/ec3e4ca8-2359-4a9b-a5b3-1be1a05af10f
> > Below is the HifiGan OFF output. https://github.com/JarodMica/ai-voice-cloning/assets/51301116/d08612e8-3291-4d26-bab6-d038bf11233b
> > may i know is this normal or just me?
> > Thank you very much for your time.
> 
> Hi Michell,
> 
> Your observation is correct. When you turn HifiGAN on, it replaces the diffusion component of the pipeline and since sample and iterations are specific to the diffusion component, it has no effect.
> 
> When you turn HifiGAN off, it loads the diffusion model and you can now play around with iteration and sample. 512 for sample is quite extreme and I'd never suggest going that high as the cost/performance isn't worth it. My suggestion would be 32 at max for samples.


Thank you very much for your prompt reply.
