### ISSUE TITLE
Please update DeepSpeed to the latest version 0.13.1

### ISSUE THREAD

**Issue by AhmedGit** [JarodMica/ai-voice-cloning#27]
Thanks for the very very greate work.

Update DeepSpeed to the latest version using the build procedure in here, and if possible update to the latest torch 12.1, and python 10.

https://github.com/S95Sedan/Deepspeed-Windows

**Comment by JarodMica** [comment]
Will only upgrade if there are significant positives for doing so.  The current DeepSpeed works fine and haven't noticed any issues. 

Closing as it's a non-issue.
