### ISSUE TITLE
whisper large-v3 support?

### ISSUE THREAD

**Issue by hopto-dot** [JarodMica/ai-voice-cloning#3]
[Full model](https://huggingface.co/openai/whisper-large-v3)

there is a [faster whisper large-v3](https://huggingface.co/bababababooey/faster-whisper-large-v3) model too

**Comment by JarodMica** [comment]
Completely forgot they had released this model. I'll have to look into how this could get added as it should be usable with whisperx

**Comment by JarodMica** [comment]
Compatibility added to the repo

**Comment by Vektor369** [comment]
How do we implement this? What files do we need, and where do we put them?
Thanks in advance.
