### ISSUE TITLE
huggingface download ai-voice-cloning 7zip  integrity not good 

### ISSUE THREAD

**Issue by brcisna** [JarodMica/ai-voice-cloning#32]
I know this isnt really the place to post but do not see any place in huggyface to report a problem.

The current ai-voice-cloning / 7zip file  never downloads to where i get a good integrity check once it has been downloaded.
I always run an integrity check on huge files like this before i even try and extract 
If i go ahead and do an extract it does of course complete but with errors. Have tried 5 times now.

**Comment by JarodMica** [comment]
Usually extraction errors come from either: 3rd party 7zip extractor or your 7zip extractor needs to be updated. The one that comed with windows 11 results in errors I believe as others have reported to me, so I recommend the original 7zip.

**Comment by JarodMica** [comment]
No resolution, feel free to open back up if you are still having issues.
