### ISSUE TITLE
API integration

### ISSUE THREAD

**Issue by Jonathan-v-S** [JarodMica/ai-voice-cloning#33]
I'd love to be able to link the new features to other apps with a simple API, can imagine that's the case for others too. I want to help out writing it if you need an extra pair of hands. Super work on the project!

**Comment by JarodMica** [comment]
Thank you! It comes with an API via Gradio, so if you wanted to make a post to it you could there (is that what you're looking for?).  If you create some other functionality and want to share it, feel free to PR and I'll review it.

Closing as non-issue.

**Comment by Jonathan-v-S** [comment]
Thanks for your response, I'll look into the gradio api! I'll explain what I'm trying to do: I'm working on new functionality that would enable to directly link TTS to an uploaded .epub / .pdf file and go through it sentence by sentence. It also saves where you are in the book in a json. I got a pretty decently functioning implementation ready, except for the TTS api part. I'm still learning, suggestions are welcome! I can send a link to my private GH repo if you're interested. It's nothing like repo but it's something :)
