### ISSUE TITLE
ModuleNotFoundError: No module named 'rvc_pipe'

### ISSUE THREAD

**Issue by anzestrela** [JarodMica/ai-voice-cloning#34]
I downloaded the v2 zip version, created venv and did pip install -r requirements.txt.

but when I try to run the program I get:
`
Traceback (most recent call last):
  File "/home/anzestrela/tts/ai-voice-cloning/./src/main.py", line 20, in <module>
    from utils import *
  File "/home/anzestrela/tts/ai-voice-cloning/src/utils.py", line 45, in <module>
    from rvc_pipe.rvc_infer import rvc_convert
ModuleNotFoundError: No module named 'rvc_pipe'`

OS: Ubuntu server
BTW: it is a PVE VM with gpu passtrough but llama.cpp is working so I think this is not the problem.

**Comment by moguldigital** [comment]
Did you find solution to this? I'm trying to run this on paperspace and this is the exact error I'm getting.

**Comment by moguldigital** [comment]
Have you tried looking into the Jarod's discord group? I don't know much coding but there is discussion there about this exact issue. You can write rvc_pipe in the search window in discord and the discussion will show up. This is the discord link: https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1ZlUVNkZnkxZDNWT29tcURJQzF1UXZBT2VLQXxBQ3Jtc0trLVpHSUlnVldqRUpTQmdoSDJtUkdwZ2R1eEZfMlRFQlNNSGRtMVU5Ml84YlFheXFVcU5Mcm0yWjd1Z1hnYkpySmJwamlDOHBSMi1rQ3ZrS1ZjcHZEYlZQXzN2R2duMEljZFNud0ZmOXduQjJQcW1FNA&q=https%3A%2F%2Fdiscord.gg%2FMym3MxcvWg&v=7tpWH8_S8es

**Comment by 2MWebs** [comment]
Getting the same error running on colab, gonna try and find a fix in the discord.

If you have trouble coding ask a GPT it will turn your english into python easy as py.

**Comment by JarodMica** [comment]
On a server, you would have to set it up manually as they run on linux.  All of the setup steps and lines you would need to call are within setup_cuda.bat, so if you could get all of that working as an .sh script and sort out the root directory for the location of rvc, you should be able to get it up and running.

Closing as linux based OS isn't supported.
