### ISSUE TITLE
Q: Generating autoregressive samples - how long it should take

### ISSUE THREAD

**Issue by jurandfantom** [JarodMica/ai-voice-cloning#4]
Hey JJ,

I got 4090 like you and I was wonder how long it suppose to take to Generating autoregressive samples  during last stage of voice cloning? In my case it takes 30 minutes for those two small clips and I have felling its not as it suppose go (training itself took 5 minutes in comparison).

Thanks for answer

**Comment by JarodMica** [comment]
Check to make sure you removed the audio files from your training into a folder named backup. If not, it tries to create a large latent file for all of the audio files you have.

As well, try with sample as 2 and iterations at 30. Samples scales pretty badly if your using the diffusion model.

**Comment by jurandfantom** [comment]
Thanks for quick answer. I figured out that i NEED "Use Hifigan instead of Diffusion." as generation speeds are like in your video after turning that on. 
Thanks for create such nice tool :)
