### ISSUE TITLE
Error with the 'tortoise.api' package.

### ISSUE THREAD

**Issue by Pineconium** [JarodMica/ai-voice-cloning#79]
So I'm trying to run the "start.sh" script and it keeps giving me this error:
`ModuleNotFoundError: No module named 'tortoise.api'`

Any help with me trying to get tortoise's API package? I installed nearly everything and I hope trying to get this pip package will be the final thing I need...

Also if anyone asks what OS I'm using it's Linux Mint 21.2

**Comment by JarodMica** [comment]
The setup with linux hasn't been refined yet for the start.sh.  There's work being done on it with #77.  If you want, I'd recommend docker as that has been fleshed out: https://github.com/JarodMica/ai-voice-cloning/pull/81
