### ISSUE TITLE
after 1st batch of text generation i got "something went wrong"

### ISSUE THREAD

**Issue by zavesone** [JarodMica/ai-voice-cloning#80]
![Screenshot 2024-04-15 004526](https://github.com/JarodMica/ai-voice-cloning/assets/109910635/533dacfd-49e6-4206-abc1-435e3ad98326)
its occures always after the 1st generation of the textmmy card Is rtx3060.

**Comment by JarodMica** [comment]
You're running out of memory, which possbily comes from using too large of reference audio.  Try to limit the amount of reference audio you're using to 5 or so seconds and only use 1 file.
